---
rules:
  missing_class_documentation:
    except:
      - lib/page_magic/exceptions.rb
  test_infection:
    except:
      - lib/page_magic/exceptions.rb
      - lib/**/exceptions.rb
      - **/exceptions.rb