Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - '.idea/**/*'
    - '*.gemspec'

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 11