Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/active_support/**/*'
    - 'spec/lib/active_support/**/*'
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - '.idea/**/*'
    - '*.gemspec'

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 11

#Style/MethodMissing:
#  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
   - 'spec/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
